// Generated by gencpp from file printeps_pepper_modules/PathGenerator.msg
// DO NOT EDIT!


#ifndef PRINTEPS_PEPPER_MODULES_MESSAGE_PATHGENERATOR_H
#define PRINTEPS_PEPPER_MODULES_MESSAGE_PATHGENERATOR_H

#include <ros/service_traits.h>


#include <printeps_pepper_modules/PathGeneratorRequest.h>
#include <printeps_pepper_modules/PathGeneratorResponse.h>


namespace printeps_pepper_modules
{

struct PathGenerator
{

typedef PathGeneratorRequest Request;
typedef PathGeneratorResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PathGenerator
} // namespace printeps_pepper_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_pepper_modules::PathGenerator > {
  static const char* value()
  {
    return "3a7361f4077151c10d6f43ed28f73c44";
  }

  static const char* value(const ::printeps_pepper_modules::PathGenerator&) { return value(); }
};

template<>
struct DataType< ::printeps_pepper_modules::PathGenerator > {
  static const char* value()
  {
    return "printeps_pepper_modules/PathGenerator";
  }

  static const char* value(const ::printeps_pepper_modules::PathGenerator&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_pepper_modules::PathGeneratorRequest> should match 
// service_traits::MD5Sum< ::printeps_pepper_modules::PathGenerator > 
template<>
struct MD5Sum< ::printeps_pepper_modules::PathGeneratorRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_pepper_modules::PathGenerator >::value();
  }
  static const char* value(const ::printeps_pepper_modules::PathGeneratorRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_pepper_modules::PathGeneratorRequest> should match 
// service_traits::DataType< ::printeps_pepper_modules::PathGenerator > 
template<>
struct DataType< ::printeps_pepper_modules::PathGeneratorRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_pepper_modules::PathGenerator >::value();
  }
  static const char* value(const ::printeps_pepper_modules::PathGeneratorRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_pepper_modules::PathGeneratorResponse> should match 
// service_traits::MD5Sum< ::printeps_pepper_modules::PathGenerator > 
template<>
struct MD5Sum< ::printeps_pepper_modules::PathGeneratorResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_pepper_modules::PathGenerator >::value();
  }
  static const char* value(const ::printeps_pepper_modules::PathGeneratorResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_pepper_modules::PathGeneratorResponse> should match 
// service_traits::DataType< ::printeps_pepper_modules::PathGenerator > 
template<>
struct DataType< ::printeps_pepper_modules::PathGeneratorResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_pepper_modules::PathGenerator >::value();
  }
  static const char* value(const ::printeps_pepper_modules::PathGeneratorResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_PEPPER_MODULES_MESSAGE_PATHGENERATOR_H
