// Generated by gencpp from file printeps_pepper_modules/PathGeneratorResponse.msg
// DO NOT EDIT!


#ifndef PRINTEPS_PEPPER_MODULES_MESSAGE_PATHGENERATORRESPONSE_H
#define PRINTEPS_PEPPER_MODULES_MESSAGE_PATHGENERATORRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/PoseArray.h>
#include <std_msgs/Float32.h>

namespace printeps_pepper_modules
{
template <class ContainerAllocator>
struct PathGeneratorResponse_
{
  typedef PathGeneratorResponse_<ContainerAllocator> Type;

  PathGeneratorResponse_()
    : path()
    , length()  {
    }
  PathGeneratorResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)
    , length(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _path_type;
  _path_type path;

   typedef  ::std_msgs::Float32_<ContainerAllocator>  _length_type;
  _length_type length;





  typedef boost::shared_ptr< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PathGeneratorResponse_

typedef ::printeps_pepper_modules::PathGeneratorResponse_<std::allocator<void> > PathGeneratorResponse;

typedef boost::shared_ptr< ::printeps_pepper_modules::PathGeneratorResponse > PathGeneratorResponsePtr;
typedef boost::shared_ptr< ::printeps_pepper_modules::PathGeneratorResponse const> PathGeneratorResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace printeps_pepper_modules

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c7ff29b7398ee8a99244f49dd44eaeb9";
  }

  static const char* value(const ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc7ff29b7398ee8a9ULL;
  static const uint64_t static_value2 = 0x9244f49dd44eaeb9ULL;
};

template<class ContainerAllocator>
struct DataType< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "printeps_pepper_modules/PathGeneratorResponse";
  }

  static const char* value(const ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/PoseArray path\n\
std_msgs/Float32 length\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: std_msgs/Float32\n\
float32 data\n\
";
  }

  static const char* value(const ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
      stream.next(m.length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathGeneratorResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::printeps_pepper_modules::PathGeneratorResponse_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.path);
    s << indent << "length: ";
    s << std::endl;
    Printer< ::std_msgs::Float32_<ContainerAllocator> >::stream(s, indent + "  ", v.length);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRINTEPS_PEPPER_MODULES_MESSAGE_PATHGENERATORRESPONSE_H
