// Generated by gencpp from file printeps_pepper_modules/PepperSpeakRequest.msg
// DO NOT EDIT!


#ifndef PRINTEPS_PEPPER_MODULES_MESSAGE_PEPPERSPEAKREQUEST_H
#define PRINTEPS_PEPPER_MODULES_MESSAGE_PEPPERSPEAKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace printeps_pepper_modules
{
template <class ContainerAllocator>
struct PepperSpeakRequest_
{
  typedef PepperSpeakRequest_<ContainerAllocator> Type;

  PepperSpeakRequest_()
    : ip_address()
    , contents()  {
    }
  PepperSpeakRequest_(const ContainerAllocator& _alloc)
    : ip_address(_alloc)
    , contents(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ip_address_type;
  _ip_address_type ip_address;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _contents_type;
  _contents_type contents;





  typedef boost::shared_ptr< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PepperSpeakRequest_

typedef ::printeps_pepper_modules::PepperSpeakRequest_<std::allocator<void> > PepperSpeakRequest;

typedef boost::shared_ptr< ::printeps_pepper_modules::PepperSpeakRequest > PepperSpeakRequestPtr;
typedef boost::shared_ptr< ::printeps_pepper_modules::PepperSpeakRequest const> PepperSpeakRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace printeps_pepper_modules

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2d992485a00c7da1c6b1cb5dbbb4c793";
  }

  static const char* value(const ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2d992485a00c7da1ULL;
  static const uint64_t static_value2 = 0xc6b1cb5dbbb4c793ULL;
};

template<class ContainerAllocator>
struct DataType< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "printeps_pepper_modules/PepperSpeakRequest";
  }

  static const char* value(const ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
string ip_address\n\
string contents\n\
";
  }

  static const char* value(const ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ip_address);
      stream.next(m.contents);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PepperSpeakRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::printeps_pepper_modules::PepperSpeakRequest_<ContainerAllocator>& v)
  {
    s << indent << "ip_address: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ip_address);
    s << indent << "contents: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.contents);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRINTEPS_PEPPER_MODULES_MESSAGE_PEPPERSPEAKREQUEST_H
