// Generated by gencpp from file printeps_pepper_modules/PepperNav.msg
// DO NOT EDIT!


#ifndef PRINTEPS_PEPPER_MODULES_MESSAGE_PEPPERNAV_H
#define PRINTEPS_PEPPER_MODULES_MESSAGE_PEPPERNAV_H

#include <ros/service_traits.h>


#include <printeps_pepper_modules/PepperNavRequest.h>
#include <printeps_pepper_modules/PepperNavResponse.h>


namespace printeps_pepper_modules
{

struct PepperNav
{

typedef PepperNavRequest Request;
typedef PepperNavResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PepperNav
} // namespace printeps_pepper_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_pepper_modules::PepperNav > {
  static const char* value()
  {
    return "cfc42ebcb6ac1e961d822c446b9526a0";
  }

  static const char* value(const ::printeps_pepper_modules::PepperNav&) { return value(); }
};

template<>
struct DataType< ::printeps_pepper_modules::PepperNav > {
  static const char* value()
  {
    return "printeps_pepper_modules/PepperNav";
  }

  static const char* value(const ::printeps_pepper_modules::PepperNav&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_pepper_modules::PepperNavRequest> should match 
// service_traits::MD5Sum< ::printeps_pepper_modules::PepperNav > 
template<>
struct MD5Sum< ::printeps_pepper_modules::PepperNavRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_pepper_modules::PepperNav >::value();
  }
  static const char* value(const ::printeps_pepper_modules::PepperNavRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_pepper_modules::PepperNavRequest> should match 
// service_traits::DataType< ::printeps_pepper_modules::PepperNav > 
template<>
struct DataType< ::printeps_pepper_modules::PepperNavRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_pepper_modules::PepperNav >::value();
  }
  static const char* value(const ::printeps_pepper_modules::PepperNavRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_pepper_modules::PepperNavResponse> should match 
// service_traits::MD5Sum< ::printeps_pepper_modules::PepperNav > 
template<>
struct MD5Sum< ::printeps_pepper_modules::PepperNavResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_pepper_modules::PepperNav >::value();
  }
  static const char* value(const ::printeps_pepper_modules::PepperNavResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_pepper_modules::PepperNavResponse> should match 
// service_traits::DataType< ::printeps_pepper_modules::PepperNav > 
template<>
struct DataType< ::printeps_pepper_modules::PepperNavResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_pepper_modules::PepperNav >::value();
  }
  static const char* value(const ::printeps_pepper_modules::PepperNavResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_PEPPER_MODULES_MESSAGE_PEPPERNAV_H
