// Generated by gencpp from file sfm_navigation/AgentArray.msg
// DO NOT EDIT!


#ifndef SFM_NAVIGATION_MESSAGE_AGENTARRAY_H
#define SFM_NAVIGATION_MESSAGE_AGENTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <sfm_navigation/Agent.h>

namespace sfm_navigation
{
template <class ContainerAllocator>
struct AgentArray_
{
  typedef AgentArray_<ContainerAllocator> Type;

  AgentArray_()
    : agents()  {
    }
  AgentArray_(const ContainerAllocator& _alloc)
    : agents(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::sfm_navigation::Agent_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::sfm_navigation::Agent_<ContainerAllocator> >::other >  _agents_type;
  _agents_type agents;





  typedef boost::shared_ptr< ::sfm_navigation::AgentArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sfm_navigation::AgentArray_<ContainerAllocator> const> ConstPtr;

}; // struct AgentArray_

typedef ::sfm_navigation::AgentArray_<std::allocator<void> > AgentArray;

typedef boost::shared_ptr< ::sfm_navigation::AgentArray > AgentArrayPtr;
typedef boost::shared_ptr< ::sfm_navigation::AgentArray const> AgentArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sfm_navigation::AgentArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sfm_navigation::AgentArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace sfm_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sfm_navigation': ['/catkin_ws/src/sfm_navigation/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::sfm_navigation::AgentArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sfm_navigation::AgentArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sfm_navigation::AgentArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sfm_navigation::AgentArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sfm_navigation::AgentArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sfm_navigation::AgentArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sfm_navigation::AgentArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a42d8b787a4b74273a3d435730aaf001";
  }

  static const char* value(const ::sfm_navigation::AgentArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa42d8b787a4b7427ULL;
  static const uint64_t static_value2 = 0x3a3d435730aaf001ULL;
};

template<class ContainerAllocator>
struct DataType< ::sfm_navigation::AgentArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sfm_navigation/AgentArray";
  }

  static const char* value(const ::sfm_navigation::AgentArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sfm_navigation::AgentArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sfm_navigation/Agent[] agents\n\
================================================================================\n\
MSG: sfm_navigation/Agent\n\
geometry_msgs/Pose2D  pose\n\
geometry_msgs/Twist twist\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Twist\n\
# This expresses velocity in free space broken into its linear and angular parts.\n\
Vector3  linear\n\
Vector3  angular\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Vector3\n\
# This represents a vector in free space. \n\
# It is only meant to represent a direction. Therefore, it does not\n\
# make sense to apply a translation to it (e.g., when applying a \n\
# generic rigid transformation to a Vector3, tf2 will only apply the\n\
# rotation). If you want your data to be translatable too, use the\n\
# geometry_msgs/Point message instead.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::sfm_navigation::AgentArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sfm_navigation::AgentArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agents);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgentArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sfm_navigation::AgentArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sfm_navigation::AgentArray_<ContainerAllocator>& v)
  {
    s << indent << "agents[]" << std::endl;
    for (size_t i = 0; i < v.agents.size(); ++i)
    {
      s << indent << "  agents[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::sfm_navigation::Agent_<ContainerAllocator> >::stream(s, indent + "    ", v.agents[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SFM_NAVIGATION_MESSAGE_AGENTARRAY_H
