# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from printeps_hsr_modules/HsrObstacleArray.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import printeps_hsr_modules.msg
import geometry_msgs.msg

class HsrObstacleArray(genpy.Message):
  _md5sum = "7e3b0fff0352a3b8fd7f25ac5227d549"
  _type = "printeps_hsr_modules/HsrObstacleArray"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """HsrTableset[]   obstacles
================================================================================
MSG: printeps_hsr_modules/HsrTableset

HsrObstacle     table
HsrObstacle[]   chairs
================================================================================
MSG: printeps_hsr_modules/HsrObstacle
geometry_msgs/Pose2D  pose
float32 width
================================================================================
MSG: geometry_msgs/Pose2D
# Deprecated
# Please use the full 3D pose.

# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.

# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.


# This expresses a position and orientation on a 2D manifold.

float64 x
float64 y
float64 theta
"""
  __slots__ = ['obstacles']
  _slot_types = ['printeps_hsr_modules/HsrTableset[]']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       obstacles

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(HsrObstacleArray, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.obstacles is None:
        self.obstacles = []
    else:
      self.obstacles = []

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      length = len(self.obstacles)
      buff.write(_struct_I.pack(length))
      for val1 in self.obstacles:
        _v1 = val1.table
        _v2 = _v1.pose
        _x = _v2
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
        buff.write(_get_struct_f().pack(_v1.width))
        length = len(val1.chairs)
        buff.write(_struct_I.pack(length))
        for val2 in val1.chairs:
          _v3 = val2.pose
          _x = _v3
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
          buff.write(_get_struct_f().pack(val2.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.obstacles is None:
        self.obstacles = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obstacles = []
      for i in range(0, length):
        val1 = printeps_hsr_modules.msg.HsrTableset()
        _v4 = val1.table
        _v5 = _v4.pose
        _x = _v5
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (_v4.width,) = _get_struct_f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.chairs = []
        for i in range(0, length):
          val2 = printeps_hsr_modules.msg.HsrObstacle()
          _v6 = val2.pose
          _x = _v6
          start = end
          end += 24
          (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (val2.width,) = _get_struct_f().unpack(str[start:end])
          val1.chairs.append(val2)
        self.obstacles.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      length = len(self.obstacles)
      buff.write(_struct_I.pack(length))
      for val1 in self.obstacles:
        _v7 = val1.table
        _v8 = _v7.pose
        _x = _v8
        buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
        buff.write(_get_struct_f().pack(_v7.width))
        length = len(val1.chairs)
        buff.write(_struct_I.pack(length))
        for val2 in val1.chairs:
          _v9 = val2.pose
          _x = _v9
          buff.write(_get_struct_3d().pack(_x.x, _x.y, _x.theta))
          buff.write(_get_struct_f().pack(val2.width))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.obstacles is None:
        self.obstacles = None
      end = 0
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      self.obstacles = []
      for i in range(0, length):
        val1 = printeps_hsr_modules.msg.HsrTableset()
        _v10 = val1.table
        _v11 = _v10.pose
        _x = _v11
        start = end
        end += 24
        (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
        start = end
        end += 4
        (_v10.width,) = _get_struct_f().unpack(str[start:end])
        start = end
        end += 4
        (length,) = _struct_I.unpack(str[start:end])
        val1.chairs = []
        for i in range(0, length):
          val2 = printeps_hsr_modules.msg.HsrObstacle()
          _v12 = val2.pose
          _x = _v12
          start = end
          end += 24
          (_x.x, _x.y, _x.theta,) = _get_struct_3d().unpack(str[start:end])
          start = end
          end += 4
          (val2.width,) = _get_struct_f().unpack(str[start:end])
          val1.chairs.append(val2)
        self.obstacles.append(val1)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_f = None
def _get_struct_f():
    global _struct_f
    if _struct_f is None:
        _struct_f = struct.Struct("<f")
    return _struct_f
_struct_3d = None
def _get_struct_3d():
    global _struct_3d
    if _struct_3d is None:
        _struct_3d = struct.Struct("<3d")
    return _struct_3d
