// Generated by gencpp from file printeps_hsr_modules/Float32ToPose2D.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_FLOAT32TOPOSE2D_H
#define PRINTEPS_HSR_MODULES_MESSAGE_FLOAT32TOPOSE2D_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/Float32ToPose2DRequest.h>
#include <printeps_hsr_modules/Float32ToPose2DResponse.h>


namespace printeps_hsr_modules
{

struct Float32ToPose2D
{

typedef Float32ToPose2DRequest Request;
typedef Float32ToPose2DResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Float32ToPose2D
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::Float32ToPose2D > {
  static const char* value()
  {
    return "595198faf2d4ff1d9d56604b59c791ea";
  }

  static const char* value(const ::printeps_hsr_modules::Float32ToPose2D&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::Float32ToPose2D > {
  static const char* value()
  {
    return "printeps_hsr_modules/Float32ToPose2D";
  }

  static const char* value(const ::printeps_hsr_modules::Float32ToPose2D&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::Float32ToPose2DRequest> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::Float32ToPose2D > 
template<>
struct MD5Sum< ::printeps_hsr_modules::Float32ToPose2DRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::Float32ToPose2D >::value();
  }
  static const char* value(const ::printeps_hsr_modules::Float32ToPose2DRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::Float32ToPose2DRequest> should match 
// service_traits::DataType< ::printeps_hsr_modules::Float32ToPose2D > 
template<>
struct DataType< ::printeps_hsr_modules::Float32ToPose2DRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::Float32ToPose2D >::value();
  }
  static const char* value(const ::printeps_hsr_modules::Float32ToPose2DRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::Float32ToPose2DResponse> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::Float32ToPose2D > 
template<>
struct MD5Sum< ::printeps_hsr_modules::Float32ToPose2DResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::Float32ToPose2D >::value();
  }
  static const char* value(const ::printeps_hsr_modules::Float32ToPose2DResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::Float32ToPose2DResponse> should match 
// service_traits::DataType< ::printeps_hsr_modules::Float32ToPose2D > 
template<>
struct DataType< ::printeps_hsr_modules::Float32ToPose2DResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::Float32ToPose2D >::value();
  }
  static const char* value(const ::printeps_hsr_modules::Float32ToPose2DResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_FLOAT32TOPOSE2D_H
