// Generated by gencpp from file printeps_hsr_modules/HsrCarry2017.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRCARRY2017_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRCARRY2017_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrCarry2017Request.h>
#include <printeps_hsr_modules/HsrCarry2017Response.h>


namespace printeps_hsr_modules
{

struct HsrCarry2017
{

typedef HsrCarry2017Request Request;
typedef HsrCarry2017Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrCarry2017
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrCarry2017 > {
  static const char* value()
  {
    return "2dce38ab0b77cebc740f59d7c59f16d4";
  }

  static const char* value(const ::printeps_hsr_modules::HsrCarry2017&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrCarry2017 > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrCarry2017";
  }

  static const char* value(const ::printeps_hsr_modules::HsrCarry2017&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrCarry2017Request> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrCarry2017 > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrCarry2017Request>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrCarry2017 >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrCarry2017Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrCarry2017Request> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrCarry2017 > 
template<>
struct DataType< ::printeps_hsr_modules::HsrCarry2017Request>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrCarry2017 >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrCarry2017Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrCarry2017Response> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrCarry2017 > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrCarry2017Response>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrCarry2017 >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrCarry2017Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrCarry2017Response> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrCarry2017 > 
template<>
struct DataType< ::printeps_hsr_modules::HsrCarry2017Response>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrCarry2017 >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrCarry2017Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRCARRY2017_H
