// Generated by gencpp from file printeps_hsr_modules/HsrCarry2017Request.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRCARRY2017REQUEST_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRCARRY2017REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace printeps_hsr_modules
{
template <class ContainerAllocator>
struct HsrCarry2017Request_
{
  typedef HsrCarry2017Request_<ContainerAllocator> Type;

  HsrCarry2017Request_()
    : pose_B()
    , pose_D()  {
    }
  HsrCarry2017Request_(const ContainerAllocator& _alloc)
    : pose_B(_alloc)
    , pose_D(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pose_B_type;
  _pose_B_type pose_B;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _pose_D_type;
  _pose_D_type pose_D;





  typedef boost::shared_ptr< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> const> ConstPtr;

}; // struct HsrCarry2017Request_

typedef ::printeps_hsr_modules::HsrCarry2017Request_<std::allocator<void> > HsrCarry2017Request;

typedef boost::shared_ptr< ::printeps_hsr_modules::HsrCarry2017Request > HsrCarry2017RequestPtr;
typedef boost::shared_ptr< ::printeps_hsr_modules::HsrCarry2017Request const> HsrCarry2017RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace printeps_hsr_modules

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'printeps_hsr_modules': ['/catkin_ws/src/printeps_hsr_modules/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e9449a3264318b456993b7e3b0714d6";
  }

  static const char* value(const ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e9449a3264318b4ULL;
  static const uint64_t static_value2 = 0x56993b7e3b0714d6ULL;
};

template<class ContainerAllocator>
struct DataType< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "printeps_hsr_modules/HsrCarry2017Request";
  }

  static const char* value(const ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
string  pose_B\n\
string  pose_D\n\
";
  }

  static const char* value(const ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose_B);
      stream.next(m.pose_D);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HsrCarry2017Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::printeps_hsr_modules::HsrCarry2017Request_<ContainerAllocator>& v)
  {
    s << indent << "pose_B: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pose_B);
    s << indent << "pose_D: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.pose_D);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRCARRY2017REQUEST_H
