// Generated by gencpp from file printeps_hsr_modules/HsrCarry.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRCARRY_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRCARRY_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrCarryRequest.h>
#include <printeps_hsr_modules/HsrCarryResponse.h>


namespace printeps_hsr_modules
{

struct HsrCarry
{

typedef HsrCarryRequest Request;
typedef HsrCarryResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrCarry
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrCarry > {
  static const char* value()
  {
    return "a8b810758ea760dd74984f070e767d53";
  }

  static const char* value(const ::printeps_hsr_modules::HsrCarry&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrCarry > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrCarry";
  }

  static const char* value(const ::printeps_hsr_modules::HsrCarry&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrCarryRequest> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrCarry > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrCarryRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrCarry >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrCarryRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrCarryRequest> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrCarry > 
template<>
struct DataType< ::printeps_hsr_modules::HsrCarryRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrCarry >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrCarryRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrCarryResponse> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrCarry > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrCarryResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrCarry >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrCarryResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrCarryResponse> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrCarry > 
template<>
struct DataType< ::printeps_hsr_modules::HsrCarryResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrCarry >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrCarryResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRCARRY_H
