// Generated by gencpp from file printeps_hsr_modules/HsrHandoverObject.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRHANDOVEROBJECT_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRHANDOVEROBJECT_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrHandoverObjectRequest.h>
#include <printeps_hsr_modules/HsrHandoverObjectResponse.h>


namespace printeps_hsr_modules
{

struct HsrHandoverObject
{

typedef HsrHandoverObjectRequest Request;
typedef HsrHandoverObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrHandoverObject
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrHandoverObject > {
  static const char* value()
  {
    return "2699cab027d5696828aa7d5692db4bfe";
  }

  static const char* value(const ::printeps_hsr_modules::HsrHandoverObject&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrHandoverObject > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrHandoverObject";
  }

  static const char* value(const ::printeps_hsr_modules::HsrHandoverObject&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrHandoverObjectRequest> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrHandoverObject > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrHandoverObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrHandoverObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrHandoverObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrHandoverObjectRequest> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrHandoverObject > 
template<>
struct DataType< ::printeps_hsr_modules::HsrHandoverObjectRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrHandoverObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrHandoverObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrHandoverObjectResponse> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrHandoverObject > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrHandoverObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrHandoverObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrHandoverObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrHandoverObjectResponse> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrHandoverObject > 
template<>
struct DataType< ::printeps_hsr_modules::HsrHandoverObjectResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrHandoverObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrHandoverObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRHANDOVEROBJECT_H
