// Generated by gencpp from file printeps_hsr_modules/HsrLog.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRLOG_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRLOG_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrLogRequest.h>
#include <printeps_hsr_modules/HsrLogResponse.h>


namespace printeps_hsr_modules
{

struct HsrLog
{

typedef HsrLogRequest Request;
typedef HsrLogResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrLog
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrLog > {
  static const char* value()
  {
    return "9e0a21f8f1cdf5a53b46ee0aee2923c4";
  }

  static const char* value(const ::printeps_hsr_modules::HsrLog&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrLog > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrLog";
  }

  static const char* value(const ::printeps_hsr_modules::HsrLog&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrLogRequest> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrLog > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrLogRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrLog >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrLogRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrLogRequest> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrLog > 
template<>
struct DataType< ::printeps_hsr_modules::HsrLogRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrLog >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrLogRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrLogResponse> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrLog > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrLogResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrLog >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrLogResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrLogResponse> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrLog > 
template<>
struct DataType< ::printeps_hsr_modules::HsrLogResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrLog >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrLogResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRLOG_H
