// Generated by gencpp from file printeps_hsr_modules/HsrLogPRequest.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRLOGPREQUEST_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRLOGPREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace printeps_hsr_modules
{
template <class ContainerAllocator>
struct HsrLogPRequest_
{
  typedef HsrLogPRequest_<ContainerAllocator> Type;

  HsrLogPRequest_()
    : log(false)
    , PCD(false)
    , mode()  {
    }
  HsrLogPRequest_(const ContainerAllocator& _alloc)
    : log(false)
    , PCD(false)
    , mode(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _log_type;
  _log_type log;

   typedef uint8_t _PCD_type;
  _PCD_type PCD;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HsrLogPRequest_

typedef ::printeps_hsr_modules::HsrLogPRequest_<std::allocator<void> > HsrLogPRequest;

typedef boost::shared_ptr< ::printeps_hsr_modules::HsrLogPRequest > HsrLogPRequestPtr;
typedef boost::shared_ptr< ::printeps_hsr_modules::HsrLogPRequest const> HsrLogPRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace printeps_hsr_modules

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'printeps_hsr_modules': ['/catkin_ws/src/printeps_hsr_modules/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b88fe43ad11f445b9f157d1b0449bf95";
  }

  static const char* value(const ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb88fe43ad11f445bULL;
  static const uint64_t static_value2 = 0x9f157d1b0449bf95ULL;
};

template<class ContainerAllocator>
struct DataType< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "printeps_hsr_modules/HsrLogPRequest";
  }

  static const char* value(const ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
bool log\n\
bool PCD\n\
string mode\n\
";
  }

  static const char* value(const ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.log);
      stream.next(m.PCD);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HsrLogPRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::printeps_hsr_modules::HsrLogPRequest_<ContainerAllocator>& v)
  {
    s << indent << "log: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.log);
    s << indent << "PCD: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.PCD);
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRLOGPREQUEST_H
