// Generated by gencpp from file printeps_hsr_modules/HsrMMNav.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRMMNAV_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRMMNAV_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrMMNavRequest.h>
#include <printeps_hsr_modules/HsrMMNavResponse.h>


namespace printeps_hsr_modules
{

struct HsrMMNav
{

typedef HsrMMNavRequest Request;
typedef HsrMMNavResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrMMNav
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrMMNav > {
  static const char* value()
  {
    return "6c1ad0746ba7a1849f6940921095b943";
  }

  static const char* value(const ::printeps_hsr_modules::HsrMMNav&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrMMNav > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrMMNav";
  }

  static const char* value(const ::printeps_hsr_modules::HsrMMNav&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrMMNavRequest> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrMMNav > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrMMNavRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrMMNav >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrMMNavRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrMMNavRequest> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrMMNav > 
template<>
struct DataType< ::printeps_hsr_modules::HsrMMNavRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrMMNav >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrMMNavRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrMMNavResponse> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrMMNav > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrMMNavResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrMMNav >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrMMNavResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrMMNavResponse> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrMMNav > 
template<>
struct DataType< ::printeps_hsr_modules::HsrMMNavResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrMMNav >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrMMNavResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRMMNAV_H
