// Generated by gencpp from file printeps_hsr_modules/HsrNav2.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRNAV2_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRNAV2_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrNav2Request.h>
#include <printeps_hsr_modules/HsrNav2Response.h>


namespace printeps_hsr_modules
{

struct HsrNav2
{

typedef HsrNav2Request Request;
typedef HsrNav2Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrNav2
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrNav2 > {
  static const char* value()
  {
    return "659f5d58ec18e8cceedaf86bc551955b";
  }

  static const char* value(const ::printeps_hsr_modules::HsrNav2&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrNav2 > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrNav2";
  }

  static const char* value(const ::printeps_hsr_modules::HsrNav2&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrNav2Request> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrNav2 > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrNav2Request>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrNav2 >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrNav2Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrNav2Request> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrNav2 > 
template<>
struct DataType< ::printeps_hsr_modules::HsrNav2Request>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrNav2 >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrNav2Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrNav2Response> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrNav2 > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrNav2Response>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrNav2 >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrNav2Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrNav2Response> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrNav2 > 
template<>
struct DataType< ::printeps_hsr_modules::HsrNav2Response>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrNav2 >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrNav2Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRNAV2_H
