// Generated by gencpp from file printeps_hsr_modules/HsrNav3Request.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRNAV3REQUEST_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRNAV3REQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace printeps_hsr_modules
{
template <class ContainerAllocator>
struct HsrNav3Request_
{
  typedef HsrNav3Request_<ContainerAllocator> Type;

  HsrNav3Request_()
    : pose()
    , obstacle_avoidance(false)
    , first_rot_limit(0.0)
    , velocity(0.0)  {
    }
  HsrNav3Request_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , obstacle_avoidance(false)
    , first_rot_limit(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef uint8_t _obstacle_avoidance_type;
  _obstacle_avoidance_type obstacle_avoidance;

   typedef float _first_rot_limit_type;
  _first_rot_limit_type first_rot_limit;

   typedef float _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> const> ConstPtr;

}; // struct HsrNav3Request_

typedef ::printeps_hsr_modules::HsrNav3Request_<std::allocator<void> > HsrNav3Request;

typedef boost::shared_ptr< ::printeps_hsr_modules::HsrNav3Request > HsrNav3RequestPtr;
typedef boost::shared_ptr< ::printeps_hsr_modules::HsrNav3Request const> HsrNav3RequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace printeps_hsr_modules

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'printeps_hsr_modules': ['/catkin_ws/src/printeps_hsr_modules/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "15c47ebdf07710e68bda2628420e91be";
  }

  static const char* value(const ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x15c47ebdf07710e6ULL;
  static const uint64_t static_value2 = 0x8bda2628420e91beULL;
};

template<class ContainerAllocator>
struct DataType< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "printeps_hsr_modules/HsrNav3Request";
  }

  static const char* value(const ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/Pose2D  pose\n\
bool                  obstacle_avoidance\n\
float32               first_rot_limit\n\
float32               velocity\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.obstacle_avoidance);
      stream.next(m.first_rot_limit);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HsrNav3Request_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::printeps_hsr_modules::HsrNav3Request_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "obstacle_avoidance: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.obstacle_avoidance);
    s << indent << "first_rot_limit: ";
    Printer<float>::stream(s, indent + "  ", v.first_rot_limit);
    s << indent << "velocity: ";
    Printer<float>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRNAV3REQUEST_H
