// Generated by gencpp from file printeps_hsr_modules/HsrNav3.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRNAV3_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRNAV3_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrNav3Request.h>
#include <printeps_hsr_modules/HsrNav3Response.h>


namespace printeps_hsr_modules
{

struct HsrNav3
{

typedef HsrNav3Request Request;
typedef HsrNav3Response Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrNav3
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrNav3 > {
  static const char* value()
  {
    return "ec5d44f130a88575c5041c2bf0711e81";
  }

  static const char* value(const ::printeps_hsr_modules::HsrNav3&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrNav3 > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrNav3";
  }

  static const char* value(const ::printeps_hsr_modules::HsrNav3&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrNav3Request> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrNav3 > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrNav3Request>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrNav3 >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrNav3Request&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrNav3Request> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrNav3 > 
template<>
struct DataType< ::printeps_hsr_modules::HsrNav3Request>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrNav3 >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrNav3Request&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrNav3Response> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrNav3 > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrNav3Response>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrNav3 >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrNav3Response&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrNav3Response> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrNav3 > 
template<>
struct DataType< ::printeps_hsr_modules::HsrNav3Response>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrNav3 >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrNav3Response&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRNAV3_H
