// Generated by gencpp from file printeps_hsr_modules/HsrPickUpObject.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRPICKUPOBJECT_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRPICKUPOBJECT_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrPickUpObjectRequest.h>
#include <printeps_hsr_modules/HsrPickUpObjectResponse.h>


namespace printeps_hsr_modules
{

struct HsrPickUpObject
{

typedef HsrPickUpObjectRequest Request;
typedef HsrPickUpObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrPickUpObject
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrPickUpObject > {
  static const char* value()
  {
    return "0e5e8f7cd51729cbdbf3dd95ac38dad1";
  }

  static const char* value(const ::printeps_hsr_modules::HsrPickUpObject&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrPickUpObject > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrPickUpObject";
  }

  static const char* value(const ::printeps_hsr_modules::HsrPickUpObject&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrPickUpObjectRequest> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrPickUpObject > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrPickUpObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrPickUpObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrPickUpObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrPickUpObjectRequest> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrPickUpObject > 
template<>
struct DataType< ::printeps_hsr_modules::HsrPickUpObjectRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrPickUpObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrPickUpObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrPickUpObjectResponse> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrPickUpObject > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrPickUpObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrPickUpObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrPickUpObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrPickUpObjectResponse> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrPickUpObject > 
template<>
struct DataType< ::printeps_hsr_modules::HsrPickUpObjectResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrPickUpObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrPickUpObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRPICKUPOBJECT_H
