// Generated by gencpp from file printeps_hsr_modules/HsrPlaceObject.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRPLACEOBJECT_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRPLACEOBJECT_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrPlaceObjectRequest.h>
#include <printeps_hsr_modules/HsrPlaceObjectResponse.h>


namespace printeps_hsr_modules
{

struct HsrPlaceObject
{

typedef HsrPlaceObjectRequest Request;
typedef HsrPlaceObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrPlaceObject
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrPlaceObject > {
  static const char* value()
  {
    return "2699cab027d5696828aa7d5692db4bfe";
  }

  static const char* value(const ::printeps_hsr_modules::HsrPlaceObject&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrPlaceObject > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrPlaceObject";
  }

  static const char* value(const ::printeps_hsr_modules::HsrPlaceObject&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrPlaceObjectRequest> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrPlaceObject > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrPlaceObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrPlaceObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrPlaceObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrPlaceObjectRequest> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrPlaceObject > 
template<>
struct DataType< ::printeps_hsr_modules::HsrPlaceObjectRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrPlaceObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrPlaceObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrPlaceObjectResponse> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrPlaceObject > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrPlaceObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrPlaceObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrPlaceObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrPlaceObjectResponse> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrPlaceObject > 
template<>
struct DataType< ::printeps_hsr_modules::HsrPlaceObjectResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrPlaceObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrPlaceObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRPLACEOBJECT_H
