// Generated by gencpp from file printeps_hsr_modules/HsrReleaseObject.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRRELEASEOBJECT_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRRELEASEOBJECT_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrReleaseObjectRequest.h>
#include <printeps_hsr_modules/HsrReleaseObjectResponse.h>


namespace printeps_hsr_modules
{

struct HsrReleaseObject
{

typedef HsrReleaseObjectRequest Request;
typedef HsrReleaseObjectResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrReleaseObject
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrReleaseObject > {
  static const char* value()
  {
    return "f676f5c1cafe9b38346686b35969df08";
  }

  static const char* value(const ::printeps_hsr_modules::HsrReleaseObject&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrReleaseObject > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrReleaseObject";
  }

  static const char* value(const ::printeps_hsr_modules::HsrReleaseObject&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrReleaseObjectRequest> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrReleaseObject > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrReleaseObjectRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrReleaseObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrReleaseObjectRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrReleaseObjectRequest> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrReleaseObject > 
template<>
struct DataType< ::printeps_hsr_modules::HsrReleaseObjectRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrReleaseObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrReleaseObjectRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrReleaseObjectResponse> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrReleaseObject > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrReleaseObjectResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrReleaseObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrReleaseObjectResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrReleaseObjectResponse> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrReleaseObject > 
template<>
struct DataType< ::printeps_hsr_modules::HsrReleaseObjectResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrReleaseObject >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrReleaseObjectResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRRELEASEOBJECT_H
