// Generated by gencpp from file printeps_hsr_modules/PathGeneratorRequest.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_PATHGENERATORREQUEST_H
#define PRINTEPS_HSR_MODULES_MESSAGE_PATHGENERATORREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/Pose2D.h>
#include <geometry_msgs/PoseArray.h>
#include <std_msgs/Bool.h>
#include <std_msgs/Float64.h>

namespace printeps_hsr_modules
{
template <class ContainerAllocator>
struct PathGeneratorRequest_
{
  typedef PathGeneratorRequest_<ContainerAllocator> Type;

  PathGeneratorRequest_()
    : start()
    , goal()
    , dynamicObstacle()
    , multimodalPathplanning()
    , voiceImportance()  {
    }
  PathGeneratorRequest_(const ContainerAllocator& _alloc)
    : start(_alloc)
    , goal(_alloc)
    , dynamicObstacle(_alloc)
    , multimodalPathplanning(_alloc)
    , voiceImportance(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _start_type;
  _start_type start;

   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _goal_type;
  _goal_type goal;

   typedef  ::geometry_msgs::PoseArray_<ContainerAllocator>  _dynamicObstacle_type;
  _dynamicObstacle_type dynamicObstacle;

   typedef  ::std_msgs::Bool_<ContainerAllocator>  _multimodalPathplanning_type;
  _multimodalPathplanning_type multimodalPathplanning;

   typedef  ::std_msgs::Float64_<ContainerAllocator>  _voiceImportance_type;
  _voiceImportance_type voiceImportance;





  typedef boost::shared_ptr< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> const> ConstPtr;

}; // struct PathGeneratorRequest_

typedef ::printeps_hsr_modules::PathGeneratorRequest_<std::allocator<void> > PathGeneratorRequest;

typedef boost::shared_ptr< ::printeps_hsr_modules::PathGeneratorRequest > PathGeneratorRequestPtr;
typedef boost::shared_ptr< ::printeps_hsr_modules::PathGeneratorRequest const> PathGeneratorRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace printeps_hsr_modules

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'printeps_hsr_modules': ['/catkin_ws/src/printeps_hsr_modules/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6cfcca9441d2ae484b67236b2a34afde";
  }

  static const char* value(const ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6cfcca9441d2ae48ULL;
  static const uint64_t static_value2 = 0x4b67236b2a34afdeULL;
};

template<class ContainerAllocator>
struct DataType< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "printeps_hsr_modules/PathGeneratorRequest";
  }

  static const char* value(const ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/Pose2D    start\n\
geometry_msgs/Pose2D    goal\n\
geometry_msgs/PoseArray dynamicObstacle\n\
std_msgs/Bool           multimodalPathplanning\n\
std_msgs/Float64         voiceImportance\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
\n\
================================================================================\n\
MSG: geometry_msgs/PoseArray\n\
# An array of poses with a header for global reference.\n\
\n\
Header header\n\
\n\
Pose[] poses\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of position and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
\n\
================================================================================\n\
MSG: std_msgs/Bool\n\
bool data\n\
================================================================================\n\
MSG: std_msgs/Float64\n\
float64 data\n\
";
  }

  static const char* value(const ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.start);
      stream.next(m.goal);
      stream.next(m.dynamicObstacle);
      stream.next(m.multimodalPathplanning);
      stream.next(m.voiceImportance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathGeneratorRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::printeps_hsr_modules::PathGeneratorRequest_<ContainerAllocator>& v)
  {
    s << indent << "start: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.start);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
    s << indent << "dynamicObstacle: ";
    s << std::endl;
    Printer< ::geometry_msgs::PoseArray_<ContainerAllocator> >::stream(s, indent + "  ", v.dynamicObstacle);
    s << indent << "multimodalPathplanning: ";
    s << std::endl;
    Printer< ::std_msgs::Bool_<ContainerAllocator> >::stream(s, indent + "  ", v.multimodalPathplanning);
    s << indent << "voiceImportance: ";
    s << std::endl;
    Printer< ::std_msgs::Float64_<ContainerAllocator> >::stream(s, indent + "  ", v.voiceImportance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_PATHGENERATORREQUEST_H
