// Generated by gencpp from file printeps_hsr_modules/Float32ToPose2DResponse.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_FLOAT32TOPOSE2DRESPONSE_H
#define PRINTEPS_HSR_MODULES_MESSAGE_FLOAT32TOPOSE2DRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace printeps_hsr_modules
{
template <class ContainerAllocator>
struct Float32ToPose2DResponse_
{
  typedef Float32ToPose2DResponse_<ContainerAllocator> Type;

  Float32ToPose2DResponse_()
    : pose2d()  {
    }
  Float32ToPose2DResponse_(const ContainerAllocator& _alloc)
    : pose2d(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _pose2d_type;
  _pose2d_type pose2d;





  typedef boost::shared_ptr< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> const> ConstPtr;

}; // struct Float32ToPose2DResponse_

typedef ::printeps_hsr_modules::Float32ToPose2DResponse_<std::allocator<void> > Float32ToPose2DResponse;

typedef boost::shared_ptr< ::printeps_hsr_modules::Float32ToPose2DResponse > Float32ToPose2DResponsePtr;
typedef boost::shared_ptr< ::printeps_hsr_modules::Float32ToPose2DResponse const> Float32ToPose2DResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace printeps_hsr_modules

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'printeps_hsr_modules': ['/catkin_ws/src/printeps_hsr_modules/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "982f3d097047fffab7774e83e9739660";
  }

  static const char* value(const ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x982f3d097047fffaULL;
  static const uint64_t static_value2 = 0xb7774e83e9739660ULL;
};

template<class ContainerAllocator>
struct DataType< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "printeps_hsr_modules/Float32ToPose2DResponse";
  }

  static const char* value(const ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D pose2d\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# Deprecated\n\
# Please use the full 3D pose.\n\
\n\
# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n\
\n\
# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n\
\n\
\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose2d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Float32ToPose2DResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::printeps_hsr_modules::Float32ToPose2DResponse_<ContainerAllocator>& v)
  {
    s << indent << "pose2d: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.pose2d);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_FLOAT32TOPOSE2DRESPONSE_H
