// Generated by gencpp from file printeps_hsr_modules/HsrHandRelease.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRHANDRELEASE_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRHANDRELEASE_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrHandReleaseRequest.h>
#include <printeps_hsr_modules/HsrHandReleaseResponse.h>


namespace printeps_hsr_modules
{

struct HsrHandRelease
{

typedef HsrHandReleaseRequest Request;
typedef HsrHandReleaseResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrHandRelease
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrHandRelease > {
  static const char* value()
  {
    return "f676f5c1cafe9b38346686b35969df08";
  }

  static const char* value(const ::printeps_hsr_modules::HsrHandRelease&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrHandRelease > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrHandRelease";
  }

  static const char* value(const ::printeps_hsr_modules::HsrHandRelease&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrHandReleaseRequest> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrHandRelease > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrHandReleaseRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrHandRelease >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrHandReleaseRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrHandReleaseRequest> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrHandRelease > 
template<>
struct DataType< ::printeps_hsr_modules::HsrHandReleaseRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrHandRelease >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrHandReleaseRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrHandReleaseResponse> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrHandRelease > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrHandReleaseResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrHandRelease >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrHandReleaseResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrHandReleaseResponse> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrHandRelease > 
template<>
struct DataType< ::printeps_hsr_modules::HsrHandReleaseResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrHandRelease >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrHandReleaseResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRHANDRELEASE_H
