// Generated by gencpp from file printeps_hsr_modules/HsrLogRequest.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRLOGREQUEST_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRLOGREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace printeps_hsr_modules
{
template <class ContainerAllocator>
struct HsrLogRequest_
{
  typedef HsrLogRequest_<ContainerAllocator> Type;

  HsrLogRequest_()
    : log(false)
    , IMU(false)
    , LRF(false)
    , Wrist(false)
    , Joint(false)
    , TF(false)
    , mode()  {
    }
  HsrLogRequest_(const ContainerAllocator& _alloc)
    : log(false)
    , IMU(false)
    , LRF(false)
    , Wrist(false)
    , Joint(false)
    , TF(false)
    , mode(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _log_type;
  _log_type log;

   typedef uint8_t _IMU_type;
  _IMU_type IMU;

   typedef uint8_t _LRF_type;
  _LRF_type LRF;

   typedef uint8_t _Wrist_type;
  _Wrist_type Wrist;

   typedef uint8_t _Joint_type;
  _Joint_type Joint;

   typedef uint8_t _TF_type;
  _TF_type TF;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mode_type;
  _mode_type mode;





  typedef boost::shared_ptr< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> const> ConstPtr;

}; // struct HsrLogRequest_

typedef ::printeps_hsr_modules::HsrLogRequest_<std::allocator<void> > HsrLogRequest;

typedef boost::shared_ptr< ::printeps_hsr_modules::HsrLogRequest > HsrLogRequestPtr;
typedef boost::shared_ptr< ::printeps_hsr_modules::HsrLogRequest const> HsrLogRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace printeps_hsr_modules

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'printeps_hsr_modules': ['/catkin_ws/src/printeps_hsr_modules/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "909d8f5ca43dce61b7fd4795a8cbeef8";
  }

  static const char* value(const ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x909d8f5ca43dce61ULL;
  static const uint64_t static_value2 = 0xb7fd4795a8cbeef8ULL;
};

template<class ContainerAllocator>
struct DataType< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "printeps_hsr_modules/HsrLogRequest";
  }

  static const char* value(const ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
bool log\n\
bool IMU\n\
bool LRF\n\
bool Wrist\n\
bool Joint\n\
bool TF\n\
string mode\n\
";
  }

  static const char* value(const ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.log);
      stream.next(m.IMU);
      stream.next(m.LRF);
      stream.next(m.Wrist);
      stream.next(m.Joint);
      stream.next(m.TF);
      stream.next(m.mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct HsrLogRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::printeps_hsr_modules::HsrLogRequest_<ContainerAllocator>& v)
  {
    s << indent << "log: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.log);
    s << indent << "IMU: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.IMU);
    s << indent << "LRF: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.LRF);
    s << indent << "Wrist: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Wrist);
    s << indent << "Joint: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.Joint);
    s << indent << "TF: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.TF);
    s << indent << "mode: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRLOGREQUEST_H
