// Generated by gencpp from file printeps_hsr_modules/HsrNav.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRNAV_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRNAV_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrNavRequest.h>
#include <printeps_hsr_modules/HsrNavResponse.h>


namespace printeps_hsr_modules
{

struct HsrNav
{

typedef HsrNavRequest Request;
typedef HsrNavResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrNav
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrNav > {
  static const char* value()
  {
    return "cfc42ebcb6ac1e961d822c446b9526a0";
  }

  static const char* value(const ::printeps_hsr_modules::HsrNav&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrNav > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrNav";
  }

  static const char* value(const ::printeps_hsr_modules::HsrNav&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrNavRequest> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrNav > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrNavRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrNav >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrNavRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrNavRequest> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrNav > 
template<>
struct DataType< ::printeps_hsr_modules::HsrNavRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrNav >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrNavRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrNavResponse> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrNav > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrNavResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrNav >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrNavResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrNavResponse> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrNav > 
template<>
struct DataType< ::printeps_hsr_modules::HsrNavResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrNav >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrNavResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRNAV_H
