// Generated by gencpp from file printeps_hsr_modules/HsrSay.msg
// DO NOT EDIT!


#ifndef PRINTEPS_HSR_MODULES_MESSAGE_HSRSAY_H
#define PRINTEPS_HSR_MODULES_MESSAGE_HSRSAY_H

#include <ros/service_traits.h>


#include <printeps_hsr_modules/HsrSayRequest.h>
#include <printeps_hsr_modules/HsrSayResponse.h>


namespace printeps_hsr_modules
{

struct HsrSay
{

typedef HsrSayRequest Request;
typedef HsrSayResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct HsrSay
} // namespace printeps_hsr_modules


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::printeps_hsr_modules::HsrSay > {
  static const char* value()
  {
    return "e42289734831209d7d09ddbae327bbad";
  }

  static const char* value(const ::printeps_hsr_modules::HsrSay&) { return value(); }
};

template<>
struct DataType< ::printeps_hsr_modules::HsrSay > {
  static const char* value()
  {
    return "printeps_hsr_modules/HsrSay";
  }

  static const char* value(const ::printeps_hsr_modules::HsrSay&) { return value(); }
};


// service_traits::MD5Sum< ::printeps_hsr_modules::HsrSayRequest> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrSay > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrSayRequest>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrSay >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrSayRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrSayRequest> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrSay > 
template<>
struct DataType< ::printeps_hsr_modules::HsrSayRequest>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrSay >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrSayRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::printeps_hsr_modules::HsrSayResponse> should match 
// service_traits::MD5Sum< ::printeps_hsr_modules::HsrSay > 
template<>
struct MD5Sum< ::printeps_hsr_modules::HsrSayResponse>
{
  static const char* value()
  {
    return MD5Sum< ::printeps_hsr_modules::HsrSay >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrSayResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::printeps_hsr_modules::HsrSayResponse> should match 
// service_traits::DataType< ::printeps_hsr_modules::HsrSay > 
template<>
struct DataType< ::printeps_hsr_modules::HsrSayResponse>
{
  static const char* value()
  {
    return DataType< ::printeps_hsr_modules::HsrSay >::value();
  }
  static const char* value(const ::printeps_hsr_modules::HsrSayResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PRINTEPS_HSR_MODULES_MESSAGE_HSRSAY_H
