(cl:defpackage printeps_pepper_modules-srv
  (:use )
  (:export
   "PATHGENERATOR"
   "<PATHGENERATOR-REQUEST>"
   "PATHGENERATOR-REQUEST"
   "<PATHGENERATOR-RESPONSE>"
   "PATHGENERATOR-RESPONSE"
   "PEPPERGLBNAV"
   "<PEPPERGLBNAV-REQUEST>"
   "PEPPERGLBNAV-REQUEST"
   "<PEPPERGLBNAV-RESPONSE>"
   "PEPPERGLBNAV-RESPONSE"
   "PEPPERNAV"
   "<PEPPERNAV-REQUEST>"
   "PEPPERNAV-REQUEST"
   "<PEPPERNAV-RESPONSE>"
   "PEPPERNAV-RESPONSE"
   "PEPPERSPEAK"
   "<PEPPERSPEAK-REQUEST>"
   "PEPPERSPEAK-REQUEST"
   "<PEPPERSPEAK-RESPONSE>"
   "PEPPERSPEAK-RESPONSE"
  ))

